- odoo80/Dockerfile
Added phantomjs because is needed for tests besides the base image is not intended for tests environments could be usefull for running local tests-
wkhtmltopdf added 0.12.1 version so there is not more warns because of this when starting instances, also this specific version is widely test
> Add extra deps

- odoo80/Dockerfile
Just moved odoo pip deps after the sh script so the are installed after the script and not before, thus the newer versions will be updated.
@moylop260 This is the version installed:
The same in the [requirements](https://github.com/Vauxoo/odoo/blob/36e9726c67cde7d4327469679fb8f36995728c73/requirements.txt#L33) file
And changed the origin to download the repos from vauxoo/odoo instead of odoo/odoo.
After this is merged I'll build all base images, then the customer images.
This close vauxoo/yoytec#362
> [FIX] Issue with reportlab.

- odoo-shippable/Dockerfile
Test zsh and Oh my zsh! into a docker container, a predefined theme is set you can look more about this theme [here](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes#schminitz-theme), 
to use it, just run:
```bash
$ docker run -t -i [IMAGE_NAME] zsh
```
> [REF] dockerfile: add zsh as alternative shell available to use

- odoo-shippable/Dockerfile
To solve [issue#54] (https://github.com/Vauxoo/docker-odoo-image/issues/54)
> [WIP][IMP] docker-odoo-image: Install ghostscript and graphviz to allow pdf prints.

- odoo-shippable/Dockerfile
Fix vim error `neocomplete requires Vim 7.3.885 or later with Lua support ("+lua")`
> [REF] odoo-shippable: Fix vim lua error 

- odoo-shippable/Dockerfile
- odoo-shippable/files/entrypoint_image
@moylop260 
Executed 2 container using the env vars:
Both containers running
Executing Psql 9.3:
Executing Psql 9.5:
With no env var (uses 9.3 as default):
As it was updated the client is now V 9.5, but the server is 9.5 or 9.3 according to the PSQL_VERSION env var, for back compatibility if no env var is given will use 9.3 by default
I changed the cluster default name to avoid conflicts even if you decice to use both versions at the same time (but the post must be changed).
The sed changing the port is necessary because pgcreatecluster don't allow me to create another cluster with the same port even when none cluster is running.
Also, added the ppostgres.wait() so it actually waits until the cluster is up, I had some issues because delayed a little to start, so decided to change this.
> [IMP] Added suppor for postgres 9.5 and multi version

- odoo-shippable/Dockerfile
- Allow use `ñ` in terminal and vim
> [REF] odoo-shippable: Fix typing special char in terminal and vim

- odoo-shippable/files/bash_colors
Currently the script to get `git status` to set the color of the branch in the prompt (red or green) is very slow with bigger git directories.
I used follow gist: https://gist.github.com/sindresorhus/3898739 to fix performance.
This script work very similar but faster.
Example:
Without changes:
With changes in versioned file:
With changes in unversioned file:
Here the difference: We have a green branch with unversioned files.
When you execute a `git add` then now is red:
This is a disadvantage but IMHO the performance issue is a greater problem.
> [FIX] odoo-shippable: Fix slow prompt in big git workdir

- odoo-shippable/Dockerfile
This change in VIM adds a set of snippets for Odoo (openerp) of the old API and new API very useful.
how to use:
[SNIPPET_WORD] < tab >
In some cases, the snippet will ask you to choose which type of API want (<7, 7 or 8)
To view the set of snippets you can see in the file ~ /.vim/bundle/vim-openerp/snippets/python.snippets and ~ /.vim/bundle/vim-openerp/snippets/xml.snippets
[Video](https://asciinema.org/a/dyg0pztxmzdesv84qsnytydow)
> [REF] odoo-shippable: Adding Odoo snippets into spf13 package

- odoo-shippable/Dockerfile
- odoo-shippable/files/entrypoint_image
- odoo-shippable/files/etc_initd_postgresql
- Based on docker image `quay.io/travisci/travis-python` to unified the use of CI script from MQT.
- Use of same path like as travis: `/etc/postgresql/9.X/main`
- Allow start/stop/restart postgresql service with `/etc/init.d/postgresql start` without a parameter additional (or one parameter if is required).
- Avoid start two psql server:
> [REF] odoo-shippable: Use of database cluster standard name and start service standard

- odoo-shippable/files/bash_colors
Use `export GIT_STATUS=1` to enable.
Use `unset GIT_STATUS` to disable.
> [REF] odoo-shippable: Enable git status prompt on-demand

- odoo80/scripts/build-image.sh
Yesterday I was trying to generate the instance for one of ours customer and the following error was raised:
Then when I tried to install the package:
@moylop260  the pycryto package is a dependency from [OMLv2](https://github.com/Vauxoo/odoo-mexico-v2/blob/8.0/l10n_mx_facturae_lib/__openerp__.py#L38), but it is not listed in the [requirements](https://github.com/Vauxoo/odoo-mexico-v2/blob/8.0/requirements.txt) file.
@LuisAlejandro besides, python-dev package is one of those that we may not need to use a lot, but since we all work (or at least most of us) with python there are a few libs that depend of it. If we want to update some of those packages we'll have to install it over and over (the idea of this image is to avoid it whenever possible)
I tested the changes in the commit and the …
> [FIX] Install pycrypto and allow the python-dev to be installed in the base image

- odoo80/scripts/build-image.sh
- odoo80/scripts/library.sh
This fixes the issues we are having with reports in lodi and others.
@nhomar @moylop260 we _cannot_ change this versions until we have everything fully tested, we had an issue in Wohlert because of this. If the idea is to improve what we already had working is ok to me, but if we are going to migrate to new versions we need a better plan that must involve the whole team so they can make the proper tests before applying this into production.
It was my bad not to check the proper package version, but still, we cannot change the fixed package versions (we had very sad times when we do this :( ) they're fixed for a very good reason (most of the time)
> [FIX] Fix the webkit version to the one that we already have working

- odoo-shippable/scripts/build-image.sh
**Results**
After implement the installation and configuration of git `diff-highlight` in a local docker-odoo-image the project images have the following behaviour:
Closes https://github.com/Vauxoo/docker-odoo-image/issues/139
> [IMP] odoo-shippable: Add and configure diff highlight into git

- odoo-shippable/scripts/build-image.sh
ToDo:
`python3.3 -m pip --version`
> [IMP] docker-odoo-image: Install pip3 for python3.x versions

- odoo80/scripts/build-image.sh
@moylop260,
The package aded in this PR is used to generate the json with the current state of the instance and is used in all of them (currently we're installing it manually).
BTW, the packages listed [here](https://github.com/vauxoo-dev/docker-odoo-image/blob/86c645644561ee38ce3d8b8599c8fa33b31592de/odoo80/scripts/build-image.sh#L55) aren't installed, I don't know if that is a bug or expected:
That's why I had to add the package [here](https://github.com/vauxoo-dev/docker-odoo-image/blob/86c645644561ee38ce3d8b8599c8fa33b31592de/odoo80/scripts/build-image.sh#L90)
Then, as you can see:
It was installed properly.
> [ADD] Added branchesv package

- odoo-shippable/scripts/build-image.sh
The travis image quay.io/travisci/travis-python has installed the package `xvfb`
docker run -it --rm quay.io/travisci/travis-python /bin/sh -c "which Xvfb"
Output: `/usr/bin/Xvfb`
[OCA recommend us use a x server](https://github.com/OCA/maintainer-quality-tools/blob/14aa6f677f16b8fe13eb0467f5cae277a656acd7/sample_files/.travis.yml#L28-L31) in order to avoid issues using webkit (wkhtmltopdf)
> [REF] odoo-shippable: Install X server "Xvfb"

- odoo-shippable/scripts/build-image.sh
- odoo80/scripts/build-image.sh
This fixes an issue reported by @luistorresm [here](https://www.vauxoo.com/web?db=vauxoo#id=5955&view_type=form&model=project.task)  where the fonts were showing different in runbot and dev  instances.
The lack of the installed package doesn't show any error, just seems to install an additional font / font-family.
The odoo80 image now:
@moylop260 I think we should move all packages actually required by Odoo to the base image and install those required to test and dev only in the shippable image, because we end with different environments. IMHO we should have at least the same base for prod, dev and test to avoid this issues in the future. What do you think?
> [FIX] Fixed missing package in Odoo 8.0 base image

- odoo-shippable/scripts/build-image.sh
@moylop260 I was getting this error in quay.io:
It seems that the download url for ngrok have changed:
And from the site you can see that they're using this now: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
So I updated the build script to use this new one, now it is installed properly:
> [FIX] Error with ngrok not being installed

- odoo-shippable/scripts/build-image.sh
Fix error: `/usr/local/bin/ngrok: permission denied.`
Steps to reproduce it:
`docker run --rm vauxoo/odoo-80-image-shippable-auto /usr/local/bin/ngrok --version`
`docker: Error response from daemon: oci runtime error: exec: "/usr/local/bin/ngrok": permission denied.`
Continuation of https://github.com/Vauxoo/docker-odoo-image/pull/157
> [REF] odoo-shippable: Change execution permission

- odoo80/scripts/build-image.sh
@moylop260 since we're integrating cloc with Orchest:
And this information will be gotten from all containers (including those from production) would be nice to have installed instead of installing it every time we do a deploy.
The build passed without any error and it was installed as expected:
> [ADD] Add cloc dependency

- odoo80/scripts/build-image.sh
Because is installed from addons-vauxoo requirements.txt in version required.
This PR avoid re-install the pandas packages in each t2d or production script.
> [REF] odoo80: Remove manual installation of pandas

- odoo-shippable/scripts/build-image.sh
This adds RVM support to the Odoo docker image. 
* Add mpapis public key
* Install RVM & configure shell
The problem is that this still doesn't work on its own, and requires the following change in T2D- https://github.com/Vauxoo/travis2docker/compare/master...laslabs:feature/add-rvm?expand=1
It seems that the bash profile is not being sourced during the `before_install`, even if I explicitly do `RUN /bin/bash -c "/before_install /install"`. An error about RVM not being available is output when running the aforementioned.
Along the same lines, it is not being sourced during entrypoint execution either. In this case, the gems that were installed in RVM are not available to the build.
The best part about this is that if I open an interactive shell to the container, RVM works fine:
``` …
```
> [ADD] Add RVM support

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/library.sh
@moylop260 with this you avoid to be asked for the password when try to ssh a server:
Try so ssh  with root:
And also tested adding a key to the root user:
Then added the root key to the shippable use to be sure we can connect:
With shippable (no added key):
The users can be added using ```https://github.com/<username>.keys```, with this you can keys the .pub keys the user have registered in github if you know the username, I tried with different formats for git log but only could get the actual registered name:
We have used it a few times, but in some way we have the user login, in [Orchest](https://git.vauxoo.com/vauxoo/deployv/blob/master/deployv/instance/instancev.py#L162) for example and in the Ansible files used to install the servers:
> [IMP] Avoid ssh access w/ password and block root ssh access (nor pass neither ssh-key)

- odoo80/scripts/build-image.sh
@moylop260 This should fix the latest error with m2crypto:
> [FIX] Fixed missing dependency for the latest versions of M2Crypto

- odoo-shippable/scripts/build-image.sh
Avoid the following traceback:
```bash
Generated script '/home/user/plone/zinstance/bin/buildout'.
Traceback (most recent call last):
File "bin/buildout", line 13, in <module>
import zc.buildout.buildout
File "/home/user/.buildout/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 18, in <module>
import zc.buildout.easy_install
File "/home/user/.buildout/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/easy_install.py", line 26, in <module>
import pkg_resources
File "/home/user/.buildout/eggs/setuptools-34.0.1-py2.7.egg/pkg_resources/__init__.py", line 72, in <module>
import packaging.requirements
File "/home/user/.buildout/eggs/packaging-16.8-py2.7.egg/packaging/requirements.py", line 59, in <module>
MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() …
```
> [FIX] odoo-shippable: Fix pypa/setuptools#942

- odoo80/scripts/build-image.sh
Avoid the following traceback:
```bash
Generated script '/home/user/plone/zinstance/bin/buildout'.
Traceback (most recent call last):
File "bin/buildout", line 13, in <module>
import zc.buildout.buildout
File "/home/user/.buildout/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 18, in <module>
import zc.buildout.easy_install
File "/home/user/.buildout/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/easy_install.py", line 26, in <module>
import pkg_resources
File "/home/user/.buildout/eggs/setuptools-34.0.1-py2.7.egg/pkg_resources/__init__.py", line 72, in <module>
import packaging.requirements
File "/home/user/.buildout/eggs/packaging-16.8-py2.7.egg/packaging/requirements.py", line 59, in <module>
MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() …
```
> [FIX] odoo80: Fix pypa/setuptools#942

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/entrypoint_image
- odoo-shippable/scripts/library.sh
TODO: Extra configuration for `odoo` user
Final:
> [REF] odoo-shippable: Add non root user

- odoo-shippable/scripts/build-image.sh
The section where is installed is not executed from [travis_install_nightly#L116](https://github.com/Vauxoo/maintainer-quality-tools/blob/832682c0b783b238722378d199474a86f5109f96/travis/travis_install_nightly#L116) script called. 
Fix [vauxoo/instance#348](https://git.vauxoo.com/vauxoo/instance/issues/348)
> [REF] odoo-shippable: Install pstats_print2list required cache packages

- .travis.yml
- odoo-shippable/scripts/fix-vim-snippet.py
Fix https://github.com/Vauxoo/docker-odoo-image/issues/199
This script can be run 
`python odoo-shippable/scripts/fix-vim-snippet.py --extension sh`
And the output is 
```
Snippet repeated for 'sh' named 'case'
First defined in /root/.vim/bundle/vim-snippets/UltiSnips/sh.snippets line(51:56)
+++++
Snippet defined in /root/.vim/bundle/vim-snippets/snippets/sh.snippets line(36:40)
Snippet defined in /root/.vim/bundle/vim-openerp/snippets/sh.snippets line(24:28)
+++++
Snippet repeated for 'sh' named 'elif'
First defined in /root/.vim/bundle/vim-snippets/UltiSnips/sh.snippets line(58:61)
+++++
Snippet defined in /root/.vim/bundle/vim-snippets/snippets/sh.snippets line(17:19)
Snippet defined in /root/.vim/bundle/vim-openerp/snippets/sh.snippets line(9:11)
+++++
Snippet repeated for 'sh' named …
```
> [IMP] Adding script for detecting snippet repeated

- odoo90/scripts/build-image.sh
- odoo90/scripts/library.sh
This change is made because the 8.0 and the 9.0 images are basically the same, the only differences are the pip dependencies. So we just added the corresponding file and keep everything else just the same.
This fixes the issue in abastotal instance with the reports are not being showed properly.
@moylop260 [here](https://github.com/Vauxoo/docker-odoo-image/pull/227) when we updated the 9.0 image the wkhtlmtopdf version was not updated properly. I just copied the 8.0 files and replaced to 9.0 where needed.
> [FIX] Fixed the wkhtlptopdf version.

- odoo-shippable/scripts/build-image.sh
Add python dependency `setuptools==33.1.1` in odoo-shippable image
Because this error occurs
> Add dependence setuptools odoo-shippable

- odoo100/scripts/build-image.sh
- odoo80/scripts/build-image.sh
- odoo90/scripts/build-image.sh
Now the url [http://gna.org](http://gna.org) is Inaccessible so change this url for [https://downloads.wkhtmltopdf.org](https://downloads.wkhtmltopdf.org)
The new url have all package needed in all images
> [REF] install: download.gna.org was closed

- odoo-shippable/scripts/build-image.sh
Youcompleteme required the version `g++4.9`, and the version into the imagen is `g++4.8`
> [FIX] odoo-shippable: Not install the youcompleteme

- odoo-shippable/scripts/build-image.sh
In this version of `youcompleteme` https://github.com/Valloric/YouCompleteMe/blob/c31152d34591f3211799ca1fe918eb78487e6dde/plugin/youcompleteme.vim the version required is `Vim 7.4.143.`
This is the version installed for default on odoo-shippable
With this change now the youcompleteme work fine
Fix https://github.com/Vauxoo/docker-odoo-image/issues/244
> [FIX] odoo-shippable: Install old version of youcompleteme

- odoo-shippable/scripts/build-image.sh
It is required because a few pypi packages are using svn yet :(
then this supports 'pip install svn+URL'
Example of PR where is required svn: https://github.com/OCA/connector-cmis/pull/16
> [REF] odoo-shippable: Install subversion

- odoo-shippable/scripts/build-image.sh
Now the zsh is available for `root` user and `odoo`
Fix https://github.com/Vauxoo/docker-odoo-image/issues/218
> [FIX] odoo-shippable: Install zsh for all user into the imagen

- odoo-shippable/scripts/build-image.sh
Change the default shell for root user
From `zsh` to `bash`
> [REF] odoo-shippable: Change the default console from zsh to bash to the root user

- odoo-shippable/scripts/build-image.sh
In this PR is installed the `Tmux plugin Manager`
That plugin allow install these follow plugin:
- `tmux-resurrect`
- `tmux-continuum`
- `tmux-sensible`
You can test that change cloning this repository and build the docker
`cd odoo-shippable`
`docker build -t tmux-resurrect .`
`docker run -it tmux-resurect bash`
Fix https://github.com/Vauxoo/docker-odoo-image/issues/215
> [ADD] odoo-shippable: Install tmux plugin manager

- odoo100/scripts/10.0-full_requirements.txt
- odoo100/scripts/build-image.sh
- odoo80/scripts/8.0-full_requirements.txt
- odoo80/scripts/build-image.sh
- odoo80/scripts/library.sh
- odoo90/scripts/9.0-full_requirements.txt
- odoo90/scripts/build-image.sh
Seems that a dependency is braking the install process of panama-dv and pylint-odoo, but I still can't find why and what package do that, but it seems that installing them first solve the issue by now.
@moylop260 Moving the dependencies to be installed before the requirements file seems to fix this by now, I'm still trying to find exactly what's the dependency that is braking the build because it is not panama-dv nor pylint-odoo.
I'll leave this here in case you want to use this as a workaround while I try to find the real fix for the error
> [FIX] Fix the error raised when build the image

- odoo80/scripts/build-image.sh
@JulioSerna I'll be installing the dependency you requested [here](https://git.vauxoo.com/vauxoo/orchest/issues/500#note_19301) in this image so it will be available in the big image used by runbot and all typ deployments
> [ADD] Added dependency for TyP 8.0

- odoo-shippable/scripts/build-image.sh
I put into the .bashrc file the environment variable `PYTHONPATH`, for each user.
I made one asciinema for show the functionality
[![asciicast](https://asciinema.org/a/8SI4kSduh4rwHQkNUQtaBueNc.png)](https://asciinema.org/a/8SI4kSduh4rwHQkNUQtaBueNc)
Fix https://github.com/Vauxoo/docker-odoo-image/issues/248
> [FIX] odoo-shippable: Export the PYTHONPATH inside the .bashrc

- odoo-shippable/scripts/build-image.sh
After this PR, now all files are converted to unix file format when the file is opened using VIM.
You can test this changes cloning this repository and building the docker image:
cd odoo-shippable
docker build -t vim-unix .
docker run -it vim-unix bash
> [IMP] odoo-shippable: convert all files to unix format

- odoo-shippable/scripts/build-image.sh
Reverts Vauxoo/docker-odoo-image#201
After https://github.com/Vauxoo/travis2docker/pull/95
I think that the change of coverage venv is not required
> Revert "Install coverage in the virtual environment"

- odoo-shippable/scripts/build-image.sh
When the user run the `zsh` the virtual environment of `python` and `nodejs` is not activated
> [FIX] odoo-shippable: Fix the zsh virtual environment

- odoo-shippable/scripts/build-image.sh
The command `install_plugins.sh` should be ran with the odoo user to create the folder inside the odoo home
You can test that change cloning this repository and build the docker
`cd odoo-shippable`
`docker build -t tmux-resurrect .`
`docker run -it tmux-resurect bash`
Fix https://github.com/Vauxoo/docker-odoo-image/issues/266
> [FIX] odoo-shippable: The command install_plugins.sh should be ran with the odoo user

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/entrypoint_image
- odoo80/scripts/8.0-full_requirements.txt
- odoo80/scripts/library.sh
The follow version of python they were created the virtualenv and install all dependencies of odoo
- `3.3`
- `3.4`
- `3.5`
- `3.6`
Something requirements in `odoo80/scripts/8.0-full_requirements.txt` were deleted because they are repeated
> [ADD] odoo-shippable: Adding virtualenv for each version of python installed

- odoo110/Dockerfile
- odoo110/scripts/11.0-full_requirements.txt
- odoo110/scripts/build-image.sh
- odoo110/scripts/gen_pip_deps
- odoo110/scripts/library.sh
@moylop260 this is the images that we will use for saas-18 and on (ultil Ubuntu 18.04 is released).
This depends on  https://github.com/Vauxoo/docker-ubuntu-base/pull/38
This is going to fail until that one is merged (because this uses the ubuntu 16.04-p3 image) and that one is going to fail because there is no Odoo110 folder yet (I just fixed the tests).
> [ADD] Add image for Odoo Saas 18 and preparation for 11

- odoo80/scripts/build-image.sh
- odoo90/scripts/build-image.sh
We need to install postgresql-server-dev so the pg_config commands shows the proper version, at the moment it shows 10.0 even when only the 9.6 is installed. This issue was fixed in pycopg 2.7, but not in the previous versions: https://github.com/psycopg/psycopg2/issues/594
This patch only apply for the images that uses older pycopg versions, that is 8.0 and 9.0 because 10 and 11 use 2.7.
Before this patch:
After this patch:
> [FIX] Install dev packages for postgres to avoid the exception.

- odoo-shippable/scripts/build-image.sh
@moylop260 @JesusZapata This is needed because is failing when we use 9.6 as psql version (the one used for Odoo >= 10)
> [FIX] Add users to postgres 9.6

- odoo-shippable/scripts/build-image.sh
This change is needed because the production images use python 3.5 which is the one that comes by default with Ubuntu 16.04 (the one used for all p3 odoo instances).
@moylop260 Is there any suggested P3 version for Odoo? if not this change is for having the same version as in production (3.5) also changes the pip3 default:
Which didn't match python3 default:
To 3.5:
> [FIX] Set 3.5 as default python3 and pip3 version.

- odoo-shippable/scripts/build-image.sh
Active the virtual environment in the top of the file .`bashrc` because the file `.bashrc` contains the follow sentence
```bash
[ -z "$PS1" ] && return
```
and when the gitlab-ci run using this imagen the virtual environment is not load as should be
This change will enable the possibility to use the environment variable `TRAVIS_PYTHON_VERSION` on the build of gitlab-ci
> [FIX] odoo-shippable: Active the virtual environment in the top of the .bashrc

- odoo-shippable/scripts/build-image.sh
This change is to avoid the follow mistake
I made the follow test and now the command `apt-add-repository -y "ppa:pov/wkhtmltopdf"` ran well
> [FIX] odoo-shippable: Copy the package apt_pkg from python3.4 to python3.5

- odoo110/scripts/build-image.sh
@moylop260 since the 11.0 was released we no longer need to have the saas-18 branch as main dependency source, we should be using 11.0
> [FIX] Update branches to 11.0 since that's the proper version we should be using

- odoo-shippable/scripts/build-image.sh
@moylop260 since we will be migrating in the near future to Postgresql 10.0 I'm adding it to the big image to begin the tests. I tried to do it, but I had to change too much:
What do you think about this?
> [IMP] Install Postgresql 10.0

- odoo-shippable/scripts/build-image.sh
Just as simply enable `virtualenv` plugin for zsh, showing prompt correctly
```bash
~/d/odoo-shippable git:master-zsh-virtualenv-osval ❯ docker build -f Dockerfile -t vauxoo/zshenv .
Sending build context to Docker daemon  38.91kB
...
Step 7/7 : EXPOSE 5432 8069 8070 8071 8072 22 60000-60005/udp
---> Using cache
---> 081b4fd58076
Successfully built 081b4fd58076
Successfully tagged vauxoo/zshenv:latest
~/d/odoo-shippable git:master-zsh-virtualenv-osval ❯ docker run -it --name zshenv_test --entrypoint=zsh -e LANG=en_US.UTF-8 -p 3502:8069 -itP 081b4fd58076
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
(nodejs)(python2.7) ➜  / % …
```
> [FIX] odoo-shippable: use virtualenv plugin for zsh and allow prompt elements

- odoo-shippable/scripts/build-image.sh
This change install all `lint` requirements in all `python` version installed, to avoid mistake related with `.git/hooks/pre-commit`
This change can be tester with the follow step 
- Clone this branch
- Build the imagen with the follow command `docker build -t lint_fix odoo-shippable/.`
- Made a t2d command using the previous imagen generated using one test repository ` t2d --docker-image=lint_fix git@github.com:JesusZapata/asdcust.git 11.0`
- Inside the container run the `.git/hooks/pre-commit` 
Fix https://github.com/Vauxoo/maintainer-quality-tools/issues/258
> [FIX] odoo-shippable: Install the pylint_odoo and the dependencies for each version of python installed

- odoo-shippable/scripts/build-image.sh
Currently, when the Docker image `docker-odoo-image` is built up, all modifications to the file `.bashrc` are appended at the end of the file.
Even though this behavior works just fine in most cases, it also overrides possible-user-defined settings on the file `~/.bash_aliases`, because that file is loaded before all modifications, thus making image settings taking precedence over user-defined settings.
This change re-locates the inclusion of `.bash_aliases` at the end of `~/.bashrc`, so all settings and aliases defined on `.bash_aliases` are not overridden anymore.
> [IMP] odoo-shippable: Load .bash_aliases at the end of .bashrc

- odoo110/scripts/build-image.sh
These dependencies are needed in order to implement multi website.  
According to [this](https://github.com/it-projects-llc/website-addons/blob/11.0/website_multi_company/doc/index.rst), we need the following dependencies:  
- apt:  
- ruby-compass
- gem:  
- compass
- bootstrap-sass
In order to install those dependencies, we also need:   
- apt:   
- ruby-dev, fixes:  
- autoconf, fixes:  
- automake, fixes:  
- libtool, fixes:   
- libltdl-dev, fixes:  
After all these dependencies were installed, I was able to install `compass` and `bootstrap-sass` using gem.
> [ADD] odoo110: dependencies required to implement multi website

- odoo-shippable/scripts/build-image.sh
Currrently t2d spent too much time re-installing the dependencies of pip install for each version
If we have all dependecies pre-installed for each version will be 6x faster
> [REF] odoo-shippable: Install virtualenv by each odoo version

- odoo80/scripts/8.0-full_requirements.txt
@moylop260 The version from [here](https://github.com/Vauxoo/odoo-mexico-v2/pull/541/files), after the merge the image should build with the odoo requirement and the new from omlv2
> [FIX] Update versino from omlv2

- odoo110/scripts/11.0-full_requirements.txt
The lib was updated the last Apr 14, and the method `country_codes` was
renamed by `country_codes`. Odoo calls the last method
Now: https://github.com/arthurdejong/python-stdnum/blob/d9defc8b514e5f2d9c545de23054e416bd7bd2ab/stdnum/eu/vat.py#L46
After: https://github.com/arthurdejong/python-stdnum/blame/9841baec64391567d70f2fe6c0f8a58cc27a4eee/stdnum/eu/vat.py#L46
https://github.com/odoo/odoo/blob/11.0/addons/base_vat_autocomplete/models/res_partner.py#L52
Hoy this library, is nos added in the repo requirements, but is a
depends to vatnumber.
I define the stable version that work with Odoo.
> [IMP] 11.0: Specific the version that work in Odoo

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/library.sh
Currently, custom settings for PostgreSQL, available on the image
`docker-ubuntu-base`, were not applied in the big image. One of the
consequences of that is the parameter `autovacuum` was not being
disabled.
This causes the Vauxoo's custom tune-ups to be applied in the big image,
for all installed versions.
Closes #305
> [IMP] odoo-shippable: Apply VX's custom config for all PostgreSQL

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/library.sh
This applies the following fixes, mostly related to issues due to
dropped support for Python3.3:
- Freeze virtualenv version: Starting from version 16.0, virtualenv is
not compatible with Python 3.3 anymore. Therefore, the virtualenv
version needs to be freezed for that Python version.
- Don't install virtualenv twice: virtualenv was being installed again
when creating environments for all Python versions
- Print messages when installing pip for all versions
- Fix small typos in messages printed when creating virtualenvironments
- Add a missing `$` character in the library (my bad)
- Remove redundant parameter `-p` when creating virtualenvs
- Install all Odoo versions from Vauxoo and Odoo; V11 was not being
installed
Closes #309
> [FIX] odoo-shippable: Solve issues after dropped support of Python3.3

- odoo-shippable/scripts/build-image.sh
Since MQT now requires click-odoo-makepot to construct .pot files, and
this last uses `msgmerge` to merge translation messages,  we need to add
gettext as a dependency, which provides that commandthe required command
This is one more step to solve  https://github.com/Vauxoo/maintainer-quality-tools/issues/265
> [IMP] odoo-shippable: Add gettext as a dependency

- odoo-shippable/scripts/library.sh
Currently, the LC_COLLATE environment variable is not taken into account.
Then I just forced it.
NOTE: This is a temp solution waiting for a definitive one from the ubuntu-base image.
After fix it then revert this one, please
> [REF] odoo-shippable: Force use of lc-collate=C for postgresql clusters

- odoo-shippable/Dockerfile
- odoo-shippable/scripts/build-image.sh
* 9.3 is too old and odoo has errors related with older PostgreSQL versions
- Similar to https://github.com/OCA/maintainer-quality-tools/issues/432#issuecomment-281580935
* PostgreSQL 9.3 is not supporting 'max_wal_size' configuration parameter.
- It parameter is required to configure a non-durability PostgreSQL
More info about: https://www.postgresql.org/docs/10/static/non-durability.html
* PostgreSQL 9.3 is not supporting `INSERT INTO ... ON CONFLICT DO NOTHING`
Fix https://github.com/Vauxoo/docker-odoo-image/issues/315
> [REF] odoo-shippable: Use by default postgresql 9.6 instead of 9.3

- build.py
Before this commit, the return value of the command `docker build` was
not being taken into account, thus producing false positives when the
build failed.
After this commit, the return value is taken into account and it's
returned, causing the script to return a non-zero value when the build
command returns a non-zero value.
> [FIX] build.py: Avoid false positives when build fails

- odoo-shippable/scripts/build-image.sh
* [REF] odoo-shippable: Add link symbolic python3.7-dev virtual environment for compatibility with travis.yml
https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions
* [REF] odoo-shippable: Remove custom version for 3.7
Fixed from https://github.com/odoo/odoo/pull/25841
> [REF] odoo-shippable: py3.7 stuffs

- odoo-shippable/scripts/build-image.sh
After Vauxoo's config settings for PostgreSQL were applied on #308,
PostgreSQL's logs directory changed, from within the cluster directory
to `/var/log`. Because of that, aliases referring to the old location
needs to be updated.
This sets correctly log paths in the aliases psql_log_*.
In addition, this avoids inserting an extra newline ad beginning of file
when logs are cleared.
Closes https://github.com/Vauxoo/docker-odoo-image/issues/322
> [FIX] odoo-shippable: Point PostgreSQL logs correctly on aliases

- odoo120/scripts/build-image.sh
- odoo120/scripts/library.sh
The logic to install wkhtmltopdf was changed because they didn't [packaged the xz](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5) and they packaged a .deb, so just used it.
> [IMP] Updatre wkhtmltopdf from 0.12.4 to 0.12.5

- odoo100/scripts/build-image.sh
- odoo120/scripts/build-image.sh
- odoo120/scripts/library.sh
[FIX] Proper phantom and node.
- Phantomjs intallation was failing so instead of using the one from apt install the one from the proper origin.
- Nodejs is failing in Ubuntu 18.04 so install the node repository and use the same LTS version from there (v 8.x)
The package versions are the same, but we changed the origin only. All this was needed to update all the images because a lot of packages had security issues.
@moylop260 This is the second part of the fix mentioned [here](https://github.com/Vauxoo/docker-ubuntu-base/pull/51#issuecomment-438761577)
> [FIX] Use dependencies from pip instead of the ones from apt to avoid erros

- odoo110/scripts/build-image.sh
- odoo110/scripts/library.sh
This is the dabatase file needed for GeoIP in Odoo 11.0, it is added in the default path as shown [here](https://github.com/Vauxoo/odoo/blob/11.0/odoo/tools/config.py#L277) to avoid any configuration in the instances so it'll be automatically available
> [IMP] Add GeoipLite City

- odoo-shippable/scripts/build-image.sh
Currently, Odoo is pre-downloaded for each version from 8.0 to 11.0.
However, 12.0 has been released and it's already being used in some
builds.
This causes also the version 12.0 to be downloaded, to speed up CIs of
those builds.
> [IMP] odoo-shippable: Pre-download Odoo 12.0

- .travis.yml
- odoo110/scripts/build-image.sh
- odoo110/scripts/library.sh
- odoo120/scripts/build-image.sh
This fixes the [error during the builds](https://cloud.docker.com/u/vauxoo/repository/registry-1.docker.io/vauxoo/odoo-120-image/hub-builddetail/brszt7tpzsxnztkhfgoij68) acconrding to [this comment](https://askubuntu.com/a/874551)
This should fix the error in the 11.0 image too:
- Added build for the 12.0
- Install ruby 2.5.3 in tne image for Odoo 11 using RVM and it will be available for all users (via /etc/bash.bashrc) using [this guide](https://gorails.com/setup/ubuntu/16.04#ruby-rvm) and the recomended version
- Install recomended dependencies for Ruby
- Fix the issue with gpg keys: "gpg: keyserver receive failed: No dirmngr" and the one related to old gpg version (no we use gpg2 for the keys)
> [FIX] Fix error during build with ruby dependencies

- odoo100/Dockerfile
- odoo100/scripts/build-image.sh
- odoo110/Dockerfile
- odoo110/scripts/build-image.sh
- odoo120/Dockerfile
- odoo120/scripts/build-image.sh
- odoo80/Dockerfile
- odoo80/scripts/build-image.sh
- odoo90/Dockerfile
- odoo90/scripts/build-image.sh
Since we need to control which postgres versions will be installed in the customer's instances, we will remove the installation of the postgres packages from the base image and will install them in deployv.
More info:  https://git.vauxoo.com/vauxoo/deployv/merge_requests/487
> [REF] docker-odoo-image: don't install postgres in the base images

- odoo-shippable/scripts/library.sh
Based on https://github.com/docker-library/python/commit/39c500cc8aefcb67a76d518d789441ef85fc771f#diff-ff1457e3a18eea607302812f70d21239
Fix the following error:
```bash
--2019-01-22 03:14:59-- https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz.asc
Resolving www.python.org (www.python.org)...
151.101.248.223, 2a04:4e42:3b::223
Connecting to www.python.org (www.python.org)|151.101.248.223|:443...
connected.
HTTP request sent, awaiting response...
200 OK
Length: 833 [application/octet-stream]
Saving to: ‘python.tar.xz.asc’
0K 100% 169M=0s
2019-01-22 03:14:59 (169 MB/s) - ‘python.tar.xz.asc’ saved [833/833]
gpg: keyring `/tmp/tmp.aL5HvB2O5M/secring.gpg' created
gpg: keyring `/tmp/tmp.aL5HvB2O5M/pubring.gpg' created
gpg: requesting key AA65421D from hkp server …
```
> [FIX] odoo-shippable: Fix installation py3.7

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/library.sh
- Psql 9.6 start was failing because it was removed from the base imabe since we will install the customer version that is in the vars file: https://github.com/Vauxoo/docker-odoo-image/commit/c29ca5db96e40e6e82debc71ecaaaea98770a739
- Added another 2 addresses to download the gpg keys, if one failt it should fallback to another. Hopefuly won't fail the 3
> [FIX] Fix psql install and gpg keys retreival.

- odoo100/scripts/10.0-full_requirements.txt
- odoo100/scripts/build-image.sh
- odoo100/scripts/library.sh
@moylop260 This should fix the errors from [here](https://github.com/Vauxoo/docker-ubuntu-base/pull/55) it seems that an update in unzip or gcc (I'm not sure wich one, but it seems to be unzip).
Also I didn't find any 10.0 instance that use egenix which is not updated since 2015:
\cc @keylor2906
> [FIX] Install mx-egenix-base directrly from pypi

- odoo80/scripts/8.0-full_requirements.txt
- odoo80/scripts/build-image.sh
- The installation of egenix-mx-base was failing because it seems to be incompatible with the latest versions of pip
- The pylint was failing because of the older version of setuptools
> [FIX] Fix build error.

- odoo-shippable/scripts/build-image.sh
@moylop260 The fix is a suggestion from [here](https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md)
> [FIX] Fix CVE-2019-12735

- odoo100/scripts/10.0-full_requirements.txt
This is only shown in 10.0 and saas-14 instances, all others seems to be working just fine:
This will fix it (tested in imeqmo test instance)
> [FIX] Cannot load GeoIP: Invalid GeoIP database: '/usr/share/GeoIP/GeoLite2-City.mmdb'

- odoo80/scripts/8.0-full_requirements.txt
The latest numpy version is not compatible with p2, the support was removed in 1.17.0: https://github.com/numpy/numpy/pull/12506
Also removed the pandas package from full requirements so it use the one from addons-vauxoo: https://github.com/Vauxoo/addons-vauxoo/blob/8.0/requirements.txt\#L1
> [FIX] Change pandas and numpy versions.

- odoo-shippable/scripts/build-image.sh
OCA projects are using 'mysqlclient' from requirements.txt
This package requires libmysqlclient-dev in order to avoid the following error:
- "OSError: mysql_config not found"
Travis has installed 'libmysqlclient-dev' apt package so runbot is
failing but travis is not.
In order to show the same result we are installing this dependency early
> [REF] odoo-shippable: Install 'libmysqlclient-dev' apt package

- odoo-shippable/scripts/build-image.sh
It is required just for OCA projects like:
- https://github.com/OCA/report-print-send/pull/188
> [REF] odoo-shippable: Installing libcups2-dev

- odoo-shippable/scripts/build-image.sh
Because of the last version of vim installed changed of path so the hard
coded copy of file is failing
> [FIX] odoo-shippable: Change path of vim to 8.2

- odoo-shippable/scripts/build-image.sh
- odoo100/scripts/build-image.sh
- odoo110/scripts/build-image.sh
- odoo120/scripts/build-image.sh
- odoo130/scripts/build-image.sh
- odoo90/scripts/build-image.sh
- [Watchdog drop support](https://pypi.org/project/watchdog/):
- [Geoip license](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/):
In the future we can register and get the files, for now we can use the last ones that where public
- Detect installed version of vim and use it for the path to avoid errors on updates
- For some reason 9.0 started to fail because of egenix, since we are not using this version anymoe just froze the dependencies to the ones that worked for the last time
> [FIX] watchdog dropped support for Python 2.6, 3.2 and 3.3 since 0.10.0

- odoo-shippable/scripts/build-image.sh
The output now is "Version: 2:8.2.0251-0york0~14.04" then the result was `0~14`
It is because the original regex was not scaped the dot '\.' of the version so it means any character
It is fixed adding scaped dot and now the result is "82"
It is required to copy spell files
> [FIX] odoo-shippable: Fixing vim version

- odoo-shippable/scripts/build-image.sh
- odoo-shippable/scripts/library.sh
Since that there is travis build result using coverage or pre-commit returning the following error:
File /usr/local/lib/python3.7/sqlite3/dbapi2.py, line 27, in <module>
from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
> [REF] odoo-shippable: Update python3.7.6 and check if _sqlite3 is working

- odoo100/scripts/build-image.sh
I seems that pep517 is giving some issues with the new versions of pip so the workaround is to [disable it](https://github.com/pypa/pip/pull/6370\#issuecomment-486141788).
Initially found it [here](https://bugs.launchpad.net/mistral/+bug/1867191)
This fixes:
> [FIX] Disable pep517.

- odoo-shippable/scripts/build-image.sh
Python package `pgcli` >= 3 cannot be installed anymore under python <=
3.5, as it requires the package `prompt_toolkit` 3 which is not
available for those Python versions.
As a bonus, messages printed to the log when installing pip requirements
are fixed.
> [REF] odoo-shippable: Pin version of pgcli for Python <= 3.5

- odoo-shippable/scripts/build-image.sh
Starting from Odoo v12, JS tests need Headless Chrome to run [1], which
is provided by the package `chromium-browser`.
Since the above package was not installed, JS tests were being skipped.
[1] https://github.com/odoo/odoo/commit/de84ad9c1f48
> [ADD] odoo-shippable: Add apt depend chromium-browser

- .travis.yml
- odoo-shippable/scripts/build-image.sh
Recently was released 14.0 so we need pre-cache to download it faster
I realized that 13.0 is missing so adding it
Using odoo version 14.0 as default of pylint-odoo in vim
> [REF] odoo-shippab: git pre-cache for odoo 13.0 & 14.0

- odoo110/scripts/build-image.sh
- odoo120/scripts/build-image.sh
- sphinx youtube is nop longer in bitbucker
- wkhtml* legacy versions are hosted in github now, the old url have been deprecated.
This fix:
And:
I'm only fixing the images used for current instances, the legacy ones (<11.0) won't be fixed unless needed.
> [FIX] Broken links.

- odoo110_py37/Dockerfile
Fix the `PYENV_ROOT` environment variable
Before
```bash
export PYENV_ROOT=/pyenv
export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
```
Notice `/pyenv` doesn't exists
Now
```bash
export PYENV_ROOT=/usr/share/pyenv
export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
```
> [REF] odoo110_py37: Fix PYENV_ROOT environment variable

- odoo100/scripts/build-image.sh
- odoo100/scripts/library.sh
- odoo110/scripts/build-image.sh
- odoo110/scripts/library.sh
More info about: [0.12.5-1: recommended for Odoo 10 and later.](https://github.com/odoo/odoo/wiki/Wkhtmltopdf)
> [FIX] odoo110: Using wkhtmltopdf 0.12.5-1 recommended by Odoo

- odoo100/scripts/build-image.sh
- odoo110/scripts/build-image.sh
Customer using 10.0 reported the following error:
- ![image](https://user-images.githubusercontent.com/6644187/111822112-02a2b400-88a9-11eb-99a9-6684c0b408df.png)
Another customer in 11.0
Checking old version vs new on in odoo-11.0:
`docker run -it --rm vauxoo/odoo-110-image npm -g list |grep less`
```txt
├─┬ less@4.1.1
├─┬ less-plugin-clean-css@1.5.1
│ ├── caseless@0.11.0
```
`docker run -it --rm vauxoo/odoo-110-image:wk_0_12_4 npm -g list |grep less`
```txt
├─┬ less@3.12.2
├─┬ less-plugin-clean-css@1.5.1
│ ├── caseless@0.11.0
```
Same for odoo-10.0:
`docker run -it --rm vauxoo/odoo-100-image:wk_0_12_4 npm -g list |grep less`
```txt
├─┬ less@3.11.3
│ │ ├── caseless@0.12.0
├─┬ less-plugin-clean-css@1.5.1
│ ├── caseless@0.11.0
```
`docker run -it --rm vauxoo/odoo-100-image npm -g list …
> [FIX] odoo100, odoo110: Pin less version since that odoo doesn't support newer - vx#13817

- odoo110_py37/Dockerfile
- odoo110_py37/files/odoo_cron_service.conf
Odoo using workers has a limit-timeout-real affecting the cron ones
So, the current solution is increasing the timeout
The first solution was using:
- limit_time_real_cron=0
But it raised the following error:
2021-03-25 15:28:49,497 47 ERROR DB odoo.service.server: Worker (47) Exception occured, exiting...
Traceback (most recent call last):
File "/home/odoo/instance/odoo/odoo/service/server.py", line 843, in run
t.join()
File "/usr/share/pyenv/versions/3.7.10/lib/python3.7/threading.py", line 1044, in join
self._wait_for_tstate_lock()
File "/usr/share/pyenv/versions/3.7.10/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
elif lock.acquire(block, timeout):
File "/home/odoo/instance/odoo/odoo/service/server.py", line 771, in signal_time_expired_handler
raise Exception('CPU …
> [REF] odoo110_py37: Add odoo cron service

- odoo-shippable/Dockerfile
Description of the issue/feature this PR addresses:
Currently, if numpy is available in the modules even if you are not using it
Odoo try to compile and the system is down only for a type of processor
Currently we know 2 server reproducing the error:
B&F-production
Runbot
More info about:
https://github.com/numpy/numpy/issues/17674
https://github.com/numpy/numpy/issues/17759
It is reproducing in the following MR:
https://git.vauxoo.com/vauxoo/lasec/-/merge_requests/197
Check the following discussion https://odoo-community.org/groups/contributors-15/contributors-186006?mode=thread&date_begin=&date_end=
OpenBLAS creates a number of threads equal to the number of core threads available: 56 in my case (production server),
so it quickly reached limit_memory_hard
and the process was killed …
> [ADD] odoo-shippable: add env var to avoid numpy weird errors
