odoo80/Dockerfile
This branch will be deleted, so changes are being merged into vauxoo master branch
=> [MERGE] From master in vauxoo-dev

odoo80/Dockerfile
Added dependencies because of this error in Lodi:
http://www.zimagez.com/zimage/capturadepantalla-060215-195628.php
=> Master add deps truiz

odoo-shippable/Dockerfile
=> [REF] odoo-shippable: Allow to use other user different of root

odoo80/Dockerfile
Replace download link for wkhtmltopdf because thw download repo has been moved.
=> [FIX] Fixes #22

odoo70/Dockerfile, odoo80/Dockerfile
@moylop260 this installs bash-completion package that is used in bash completion as you requested, but this will be available in all containers build from now on and all users
=> Master git completion truiz

odoo-shippable/Dockerfile
Reverts Vauxoo/docker-odoo-image#27
=> Revert "[REF] install docker in docker, install travis2docker"

odoo-shippable/Dockerfile
FIX https://github.com/Vauxoo/docker-odoo-image/issues/30
=> [ADD] odoo-shippable: Add pylint-odoo to git init hook and add openssh-server with PermitRootLogin 

odoo-shippable/Dockerfile
- FIX https://github.com/Vauxoo/docker-odoo-image/issues/33
- FIX https://github.com/Vauxoo/docker-odoo-image/issues/29
=> [REF] shippable: Enable auto-completion git and git prompt

odoo-shippable/Dockerfile
Fix #Vauxoo/docker-odoo-image#36
=> [FIX] Fix PermitRootLogin

.travis.yml
This PR respond to the #39 issue, Dockerfiles are tested but I DO need a help for more flexible travis configuration
=> [ADD] travis configuration testing docklint

odoo-shippable/Dockerfile
-  Fix comments hidden
- Enable to vim feature to select 
- Disable mouse functionallity (scroll and click to set position cursor)
=> [REF] odoo-shippable: Fix vim spf13

odoo61/Dockerfile
The purpose is fix/clean some issues with contents in all Dockerfiles contained in this repo
=> Fix Dockerfiles contents

odoo-shippable/Dockerfile, odoo-shippable/files/bash_colors
- Add bash color environment in other file.
- Add red and green color in git prompt branch name if exists changes
=> [REF] odoo-shippable: Branch name red if exists a change

odoo-shippable/Dockerfile
FIX https://github.com/Vauxoo/yoytec/issues/591
=> [IMP]increace max_conections and max_pred_lock_pre_transaction

odoo-shippable/Dockerfile
=> [REF] odoo-shippable: Change vim configuration set colorcolum 80

odoo80/Dockerfile
**IMPORTANT**: **_Do not_** merge this until vauxoo/docker-ubuntu-base#9 is merged and the image is ready
=> [FIX] Reduced the amount of RUN run lines to avoid the limit to 127 issue

odoo-shippable/Dockerfile
Spanish language was added to not display in red unknown words.
=> [IMP] Added spanish language to vim spellcheck

odoo-shippable/Dockerfile
[IMP] Update Git Version on Dockerfile
https://github.com/Vauxoo/docker-odoo-image/issues/85
=> [IMP] Update Git Version on Dockerfile

odoo-shippable/Dockerfile
- Better performance and space with `git gc`
=> [REF] odoo-shippable: Execute git gc in big git repositories

.travis.yml, odoo-shippable/Dockerfile, odoo80/Dockerfile, odoo80/scripts/build-image.sh, odoo80/scripts/library.sh, odoo90/Dockerfile, odoo90/scripts/build-image.sh, odoo90/scripts/library.sh
This is a work in progress which aims to resolve Vauxoo/docker-odoo-image#102.
=> [WIP] General improvements, updating and shrinking of odoo80 and odoo90 images

odoo80/scripts/build-image.sh
=> [FIX] Make the build script exit inmediately if a command fails.

odoo80/Dockerfile, odoo80/scripts/build-image.sh, odoo80/scripts/gen_pip_deps, odoo80/scripts/library.sh
With this we hope to avoid errors at build time like the one generated in vauxoo/docker-ubuntu-base#17.
In my local still failing with #122
=> [FIX] Allow all pip build deps installed so there are no more failing builds

odoo-shippable/Dockerfile
pylint_odoo script `install` use npm install, then we need fix it before
=> [REF] odoo-shippable: Continuation Vauxoo/docker-odoo-image#116 fix npm

odoo80/scripts/build-image.sh
=> [FIX] Correctly removing junk files from /tmp dir.

odoo-shippable/scripts/build-image.sh
=> [WIP] Fixing travis_wait

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/library.sh
Fix #135 
**ToDo:**
**Results:**
=> [FIX] odoo-shippable: Allow the fetch of another vauxoo/odoo branch

odoo-shippable/scripts/build-image.sh
=> [IMP] odoo-shippable: Enable add-apt-repository command

odoo-shippable/scripts/build-image.sh
=> [IMP] odoo-shippable: Enable javascript lints with eslint for vim

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/travis2docker/issues/72
Continuation of https://github.com/Vauxoo/docker-odoo-image/pull/155
=> [REF] odoo-shippable: Install xvfb daemon

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/superpet/issues/15
=> [REF] odoo-shippable: Install cache requirements from MQT and use ~ to home path instead of /root

.travis.yml, odoo100/Dockerfile, odoo100/scripts/build-image.sh, odoo100/scripts/gen_pip_deps, odoo100/scripts/library.sh
- Updated wkhtmltopdf to 0.12.4
- Install requirements from the 10.0 branches (Odoo, addons-vauxoo, server-tools)
- Use ubuntu 16.04
=> [ADD] Files for the odoo100 image

odoo-shippable/scripts/entrypoint_image
Study and refactor entrypoint_image according to different use cases
Referented to issue #134
=> [FIX] docker-odoo-image: Fix when the server is in another folder issue #134 

odoo-shippable/scripts/build-image.sh
[IMP] Autocomplete to replace neocomplete
=> [Vauxoo/docker-odoo-image] [IMP] Replace neocomplete by YouCompleteMe

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/library.sh
Closes https://github.com/Vauxoo/docker-odoo-image/issues/176
Closes https://github.com/Vauxoo/docker-odoo-image/issues/175
=> [REF] odoo-shippable: Install vim-wakatime plugin and other fixes

odoo-shippable/scripts/build-image.sh
Referring to https://github.com/Vauxoo/docker-odoo-image/issues/141#event-931147355
=> [IMP] Adding alias to multitail and configured multitail.conf

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/docker-odoo-image/issues/184
=> [ADD] Adding alias for rgrep and function for fetch pr

odoo-shippable/scripts/build-image.sh
Referring to https://github.com/Vauxoo/docker-odoo-image/pull/174#issuecomment-274151848
=> [IMP] Adding another PYTHONPATH in zshrc

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/docker-odoo-image/issues/186
=> [FIX] odoo-shippable: Fix skel folder with symbolic links to the root user folder

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/docker-odoo-image/issues/183
=> [ADD] odoo-shipeable: Disable auto trigger for youcompleteme

odoo-shippable/scripts/build-image.sh
@moylop260 @ruiztulio 
This fix 
```
Error detected while processing /root/.vimrc:
line 1252:
E488: Trailing characters: # Disable auto trigger for youcompleteme
Press ENTER or type command to continue
```
=> [FIX] Error detected while processing /root/.vimrc:

.travis.yml, build.py
Referring this comment https://github.com/Vauxoo/docker-odoo-image/pull/191#issuecomment-278669714 and this TODO in .travis.yml
` # TODO: Check git diff changes to build just required image.`
=> [IMP] Check if the folder has changed and then build it

odoo-shippable/scripts/build-image.sh
=> Fix when t2d trying to remove pip dependencies with non-root user

odoo-shippable/scripts/build-image.sh
=> Add environment variable to be able to perform source when user changes

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/entrypoint_image, odoo-shippable/scripts/library.sh
This PR resolves the problem of having to use sudo to be able to start or stop the postgresql service when the user is odoo
=> Allow user odoo use services postgres without sudo

odoo-shippable/scripts/build-image.sh
This PR resolves fix https://github.com/Vauxoo/odoo-peru/issues/70
=> Install coverage in the virtual environment

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/docker-odoo-image/issues/200
=> [FIX] odoo-shippable: Disable virtualenv in pymode

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/docker-odoo-image/issues/207
=> [REF] odoo-shippable: Disable vim-signify for default

odoo-shippable/scripts/library.sh
Add sql to change user password odoo
Login user odoo postgresql 9.3
Login user odoo postgresql 9.5
=> Add password to postgres user ordo

odoo-shippable/scripts/build-image.sh
Fix https://github.com/OCA/reporting-engine/issues/113
=> [REF] odoo-shippable: Install openjdk-7-jre package

odoo100/Dockerfile, odoo100/scripts/build-image.sh, odoo100/scripts/library.sh, odoo80/Dockerfile, odoo80/scripts/build-image.sh
=> [ADD] docker-odoo-image: postgresql-stats-collector high I/O

odoo-shippable/scripts/build-image.sh, odoo100/scripts/10.0-full_requirements.txt, odoo80/scripts/8.0-full_requirements.txt
Fix https://github.com/Vauxoo/enterprise-mx/issues/57
=> [ADD] odoo100: Adding requirement html2text to odoo 10.0

odoo-shippable/scripts/build-image.sh
Fix https://github.com/Vauxoo/docker-odoo-image/issues/228
=> [ADD] odoo-shippable: Install python 3.6 and python 3.6-dev

odoo-shippable/scripts/build-image.sh
Fix https://github.com/OCA/runbot-addons/issues/129
=> [FIX] odoo-shippable: Fix You don't have write permissions for the ruby directory

build.py
I made another way of calculate the diff with HEAD and show debug information about of git
=> Fix build script

odoo-shippable/scripts/build-image.sh
Because youcompleteme now required g++4.9
For the comment https://github.com/Vauxoo/docker-odoo-image/pull/240#issuecomment-309863166
=> [FIX] odoo-shippable: Disable youcompleteme for default

odoo100/scripts/10.0-full_requirements.txt, odoo80/scripts/8.0-full_requirements.txt, odoo90/scripts/9.0-full_requirements.txt
More information [here](https://www.odoo.com/es_ES/groups/community-59/community-29480376).
=> [FIX] Update psycopg version to avoid security issue

odoo80/scripts/8.0-full_requirements.txt
Related with https://github.com/OCA/maintainer-quality-tools/pull/464
=> [FIX] 8.0-full_requirements: Update the version of pyopenssl

odoo-shippable/scripts/build-image.sh
Fix issue related with the change https://github.com/Vauxoo/maintainer-quality-tools/pull/222
=> [FIX] odoo-shippable: Fix old requirements MQT path

odoo-shippable/scripts/build-image.sh
Reverts Vauxoo/docker-odoo-image#203
Fix https://github.com/Vauxoo/runbot-addons/issues/137
=> Revert "Revert "Install coverage in the virtual environment""

odoo-shippable/scripts/build-image.sh
WIP
Adding the version of python 3.2
=> [ADD] odoo-shippable: Adding another version of python 3.2

odoo-shippable/scripts/build-image.sh
Install the [tig](https://github.com/jonas/tig) to show the git history
=> [ADD] odoo-shippable: Install tig to adding more funcionality to show the git history

odoo-shippable/scripts/build-image.sh
To avoid the ssh disconnect when the console is inactive in this web page https://www.bjornjohansen.no/ssh-timeout has more information about this trouble
=> [FIX] odoo-shippable: Adding configuration over the file /etc/ssh/sshd_config

.travis.yml
This is just to enable the build of 11.0 image in travis
=> [FIX] Test 11.0 image build

odoo-shippable/scripts/build-image.sh
This change revert the follow pull request https://github.com/Vauxoo/docker-odoo-image/pull/278 to fix the follow issue https://github.com/Vauxoo/docker-odoo-image/issues/282
With this change now the branch is shown on the prompt 
Fix https://github.com/Vauxoo/docker-odoo-image/issues/282
=> [REF] odoo-shippable: Revert the follow pull request #278

odoo-shippable/scripts/build-image.sh
Install the bundle `jedi-vim` to `vim`
The bundle installed is the follow https://github.com/davidhalter/jedi-vim
=> [ADD] odoo-shippable: Install the bundle jedi-vim to vim

odoo-shippable/scripts/build-image.sh
This MR add package [PGCLI](https://www.pgcli.com/)
=> ADD pgcli to odoo-shippable

odoo-shippable/scripts/build-image.sh
Because runbot_travis2docker module tests are failing.
=>  Revert [REF] odoo-shippable: Install virtualenv by each odoo version

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/fix-vim-snippet.py
Because of https://github.com/python-mode/python-mode/issues/897
Fix https://github.com/Vauxoo/docker-odoo-image/issues/313
=> [REF] odoo-shippable: Disable pymode init and lint

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/library.sh
Fix issue https://github.com/Vauxoo/docker-odoo-image/issues/339
=> [REF] odoo-shippable: Install pyflame

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/library.sh
Revert https://github.com/Vauxoo/docker-odoo-image/pull/255
- Install newest tmux version
- Reduce history limit to save memory RAM fixing https://github.com/Vauxoo/docker-odoo-image/issues/341
=> Revert "[ADD] odoo-shippable: Install tmux plugin manager (#255)

odoo-shippable/scripts/build-image.sh
Since that vim-daily install vim7 by default better use a ppa with vim8 by default
=> [REF] odoo-shippable: Install vim8

odoo-shippable/scripts/build-image.sh
Fix the following issues:
- https://github.com/OCA/pylint-odoo/issues/202
- https://github.com/OCA/pylint-odoo/issues/222
cc @hbto
=> [REF] odoo-shippable: Disable old checks by default

odoo110/scripts/11.0-full_requirements.txt
Now Odoo support both library versions.
https://github.com/odoo/odoo/commit/c2fec7ed885ca25db29e64f2439ab4d29728294c
=> [IMP] Reverted last commit fbb1859f3628fefbe5d6f7d01f92bedd5468a4e3

odoo-shippable/scripts/build-image.sh
=> [REF] odoo-shippable: Installing black and pre-commit

odoo-shippable/scripts/build-image.sh
More info about byobu: https://byobu.org
It is similar to tmux or screen
Emacs is similar to vim
Both tools are used by @ovnicraft :)
=> [REF] odoo-shippable: Install byobu and emacs

odoo-shippable/scripts/build-image.sh
More info about: https://github.com/Vauxoo/pylint-conf/commit/a09b7a9d
=> [REF] vim: Increase colorcolumn from 80 to 120

odoo-shippable/scripts/build-image.sh, odoo-shippable/scripts/library.sh
Reverts Vauxoo/docker-odoo-image#369
It change in travis is not working well.
I will create another PR in order to fix it
=> Revert "[REF] odoo-shippable: Update python3.7.6 and check if _sqlite3 is working"

.travis.yml, odoo110_py37/Dockerfile
There is a customer using py37 with odoo v11.0 and it will be migrated to DeployV so we need to reduce variations in the package versions
=> [ADD] odoo110_py37: python37 is compatible with odoo v11.0 and it has improve performance - task#44006

odoo110_py37/Dockerfile, odoo110_py37/odoo_cron_service.conf
@moylop260 We need a few changes to make this work:
- The ones in this PR (basically a copy of the ones you deactivated + a new group)
-  A MR I made in gitlab/deployv
- An env var with the value for multi odoo environment (a MR I just made to the main rapo)
The deploy order **must be**:
- Deploy the new deployv version in the servers
- Merge this
- Afther this is done in hub.docker we can merge the one from the main repo
Regards.
=> [ADD] Add multiodoo support group for supervidor

.travis.yml, odoo150/Dockerfile, odoo150/scripts/build-image.sh, odoo150/scripts/gen_pip_deps, odoo150/scripts/library.sh
Support for the new upcomming Odoo version, expected to be released during Odoo experience and is the one we will use for the next Orchest version
=> [ADD] Add Odoo 15.0 support (wil be released in a few months)
